# Generated by Django 5.1.7 on 2025-03-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='answered_questions',
            field=models.TextField(default='[]'),
        ),
    ]
